version: '3'
services:
  web:
    image: nginx:1.18-alpine
    container_name: ngeinx-container
    volumes:
      - ./config/nginx/prod.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/aboutMe
    ports:
      - '80:80'